Getting better.  Still many problems.
1) Handling more than 1 default gateway is stil problematic
2) Determining if an address is IPv4 or IPv6 or a tunneled IPv6 is not working well.
I thought about using a heurestic, but a better approach is to read the internet
https://codefather.tech/blog/validate-ip-address-python/
3) There should be some useful functionality in layer.  I want layer to accept an
object of any class.  Then, when another object comes of the same class, compare
the two.  If different, then note the time and the change in the log.  I can get
the class name using the OBJECT.__class__ attribute.

>>> x4.__class__
<class 'ipaddress.IPv6Address'>
>>> type(x4.__class__)
<class 'type'>
>>> dq=dict()
>>> dq[type(x4.__class__)]=x4
>>> x5=ipaddress.IPv4Address('17.23.12.56'))
  File "<stdin>", line 1
    x5=ipaddress.IPv4Address('17.23.12.56'))
                                           ^
SyntaxError: unmatched ')'
>>> x5=ipaddress.IPv4Address('17.23.12.56')
>>> dq[type(x4.__class)] == dq[type(x5.__class__)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'IPv6Address' object has no attribute '__class'
>>> dq[type(x4.__class__)] == dq[type(x5.__class__)]
True
>>>
>>> dq[type(x4.__class__)]  is x4
True
>>>